# Make sure we can embed bindata
name: bindata
on:
  push:
  schedule:
    - cron: "14 17 * * 3"
jobs:
  test:
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        go: ["1.14"]
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v2
      - run: ./updatebindata.sh
      - run: go mod tidy  # revert changes caused by installing bindata
      - run: git diff --exit-code  # if this fails, run ./updatebindata.sh locally and push
