# Build and test Windows binary
name: windows
on:
  push:
  schedule:
    - cron: "14 17 * * 3"
jobs:
  build:
    runs-on: "windows-latest"
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.14"
      - uses: actions/checkout@v2
      - run: bash.exe ./build.sh windows
      - run: bash.exe ./smoketest.sh ./CLI/windows/amd64/ooniprobe.exe
      - uses: actions/upload-artifact@v1
        with:
          name: ooniprobe-windows-amd64
          path: ./CLI/windows/amd64/ooniprobe.exe
